/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PostServiceRouteImport } from './routes/post-service'
import { Route as PostJobRouteImport } from './routes/post-job'
import { Route as FindServicesRouteImport } from './routes/find-services'
import { Route as FindJobsRouteImport } from './routes/find-jobs'
import { Route as IndexRouteImport } from './routes/index'

const PostServiceRoute = PostServiceRouteImport.update({
  id: '/post-service',
  path: '/post-service',
  getParentRoute: () => rootRouteImport,
} as any)
const PostJobRoute = PostJobRouteImport.update({
  id: '/post-job',
  path: '/post-job',
  getParentRoute: () => rootRouteImport,
} as any)
const FindServicesRoute = FindServicesRouteImport.update({
  id: '/find-services',
  path: '/find-services',
  getParentRoute: () => rootRouteImport,
} as any)
const FindJobsRoute = FindJobsRouteImport.update({
  id: '/find-jobs',
  path: '/find-jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/find-jobs': typeof FindJobsRoute
  '/find-services': typeof FindServicesRoute
  '/post-job': typeof PostJobRoute
  '/post-service': typeof PostServiceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/find-jobs': typeof FindJobsRoute
  '/find-services': typeof FindServicesRoute
  '/post-job': typeof PostJobRoute
  '/post-service': typeof PostServiceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/find-jobs': typeof FindJobsRoute
  '/find-services': typeof FindServicesRoute
  '/post-job': typeof PostJobRoute
  '/post-service': typeof PostServiceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/find-jobs'
    | '/find-services'
    | '/post-job'
    | '/post-service'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/find-jobs' | '/find-services' | '/post-job' | '/post-service'
  id:
    | '__root__'
    | '/'
    | '/find-jobs'
    | '/find-services'
    | '/post-job'
    | '/post-service'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FindJobsRoute: typeof FindJobsRoute
  FindServicesRoute: typeof FindServicesRoute
  PostJobRoute: typeof PostJobRoute
  PostServiceRoute: typeof PostServiceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/post-service': {
      id: '/post-service'
      path: '/post-service'
      fullPath: '/post-service'
      preLoaderRoute: typeof PostServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post-job': {
      id: '/post-job'
      path: '/post-job'
      fullPath: '/post-job'
      preLoaderRoute: typeof PostJobRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find-services': {
      id: '/find-services'
      path: '/find-services'
      fullPath: '/find-services'
      preLoaderRoute: typeof FindServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find-jobs': {
      id: '/find-jobs'
      path: '/find-jobs'
      fullPath: '/find-jobs'
      preLoaderRoute: typeof FindJobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FindJobsRoute: FindJobsRoute,
  FindServicesRoute: FindServicesRoute,
  PostJobRoute: PostJobRoute,
  PostServiceRoute: PostServiceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
